from __future__ import annotations

import pandas as pd


def data_availability_matrix() -> pd.DataFrame:
    as_of = "2026-07-04"
    rows = [
        {
            "source": "Binance public archives/API",
            "dataset": "Spot and USD-M OHLCV",
            "estimated_cost_usd_month": 0,
            "api_key_required": False,
            "paid_plan_required": False,
            "markets": "crypto spot/futures",
            "resolution": "1m+",
            "history": "multi-year public archives",
            "backtest_ready": True,
            "forward_only": False,
            "status": "available_local",
            "limitations": "candles do not identify liquidations or book state",
            "source_url": "https://data.binance.vision/",
        },
        {
            "source": "Binance public archives/API",
            "dataset": "Aggregate trades / aggressor side",
            "estimated_cost_usd_month": 0,
            "api_key_required": False,
            "paid_plan_required": False,
            "markets": "crypto spot/futures",
            "resolution": "trade",
            "history": "public daily/monthly archives",
            "backtest_ready": True,
            "forward_only": False,
            "status": "available_not_downloaded",
            "limitations": "very large storage and processing footprint",
            "source_url": "https://data.binance.vision/",
        },
        {
            "source": "Binance USD-M Futures API",
            "dataset": "Funding rate history",
            "estimated_cost_usd_month": 0,
            "api_key_required": False,
            "paid_plan_required": False,
            "markets": "crypto perpetuals",
            "resolution": "settlement interval, usually 8h",
            "history": "paginated public endpoint",
            "backtest_ready": True,
            "forward_only": False,
            "status": "connector_ready_network_blocked",
            "limitations": "must align backward to candles; funding intervals can vary",
            "source_url": "https://developers.binance.com/docs/derivatives/usds-margined-futures/market-data/rest-api/Get-Funding-Rate-History",
        },
        {
            "source": "Binance USD-M Futures API/archives",
            "dataset": "Open interest",
            "estimated_cost_usd_month": 0,
            "api_key_required": False,
            "paid_plan_required": False,
            "markets": "crypto perpetuals",
            "resolution": "snapshot / periodic metrics",
            "history": "limited API plus public metrics archives",
            "backtest_ready": "conditional",
            "forward_only": False,
            "status": "connector_ready_network_blocked",
            "limitations": "unit and contract changes require validation",
            "source_url": "https://developers.binance.com/docs/derivatives/usds-margined-futures/market-data/rest-api/Open-Interest",
        },
        {
            "source": "Binance public WebSocket/REST",
            "dataset": "Order book and real spread",
            "estimated_cost_usd_month": 0,
            "api_key_required": False,
            "paid_plan_required": False,
            "markets": "crypto spot/futures",
            "resolution": "100ms+ / snapshot",
            "history": "no official deep historical snapshot archive",
            "backtest_ready": False,
            "forward_only": True,
            "status": "forward_collection",
            "limitations": "book reconstruction needs sequence checks and uninterrupted capture",
            "source_url": "https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams",
        },
        {
            "source": "Binance Futures WebSocket",
            "dataset": "Liquidation events",
            "estimated_cost_usd_month": 0,
            "api_key_required": False,
            "paid_plan_required": False,
            "markets": "crypto futures",
            "resolution": "event stream",
            "history": "stream only",
            "backtest_ready": False,
            "forward_only": True,
            "status": "forward_collection",
            "limitations": "collector downtime creates unobservable missing events",
            "source_url": "https://developers.binance.com/docs/derivatives/usds-margined-futures/websocket-market-streams/All-Market-Liquidation-Order-Streams",
        },
        {
            "source": "Bybit V5 public API",
            "dataset": "Funding rate history",
            "estimated_cost_usd_month": 0,
            "api_key_required": False,
            "paid_plan_required": False,
            "markets": "linear/inverse perpetuals",
            "resolution": "settlement interval",
            "history": "paginated, 200 rows/request",
            "backtest_ready": True,
            "forward_only": False,
            "status": "available_not_downloaded",
            "limitations": "cross-exchange symbol and interval normalization",
            "source_url": "https://bybit-exchange.github.io/docs/v5/market/history-fund-rate",
        },
        {
            "source": "Bybit V5 public API",
            "dataset": "Open interest",
            "estimated_cost_usd_month": 0,
            "api_key_required": False,
            "paid_plan_required": False,
            "markets": "linear/inverse contracts",
            "resolution": "5m to 1d",
            "history": "to symbol launch, paginated",
            "backtest_ready": True,
            "forward_only": False,
            "status": "available_not_downloaded",
            "limitations": "exchange differs from local Binance execution data",
            "source_url": "https://bybit-exchange.github.io/docs/v5/market/open-interest",
        },
        {
            "source": "Bybit public WebSocket",
            "dataset": "All liquidation events",
            "estimated_cost_usd_month": 0,
            "api_key_required": False,
            "paid_plan_required": False,
            "markets": "crypto derivatives",
            "resolution": "500ms push",
            "history": "stream only",
            "backtest_ready": False,
            "forward_only": True,
            "status": "forward_collection",
            "limitations": "requires continuous capture",
            "source_url": "https://bybit-exchange.github.io/docs/v5/websocket/public/all-liquidation",
        },
        {
            "source": "CoinGlass API V4",
            "dataset": "Liquidations, OI, funding, order flow",
            "estimated_cost_usd_month": 29,
            "api_key_required": True,
            "paid_plan_required": True,
            "markets": "multi-exchange crypto",
            "resolution": "plan-dependent; Hobbyist liquidation >=4h",
            "history": "plan-dependent",
            "backtest_ready": "conditional",
            "forward_only": False,
            "status": "paid_not_configured",
            "limitations": "fine intraday history requires materially higher plan",
            "source_url": "https://www.coinglass.com/pricing",
        },
        {
            "source": "Alpaca Basic IEX",
            "dataset": "US equities bars/trades/quotes",
            "estimated_cost_usd_month": 0,
            "api_key_required": True,
            "paid_plan_required": False,
            "markets": "US equities",
            "resolution": "trade/quote/1m+",
            "history": "since 2016",
            "backtest_ready": False,
            "forward_only": False,
            "status": "insufficient_for_rvol_vwap",
            "limitations": "single exchange, about 2.5% of market volume",
            "source_url": "https://docs.alpaca.markets/us/v1.1/docs/historical-stock-data-1",
        },
        {
            "source": "Alpaca Algo Trader Plus SIP",
            "dataset": "US equities consolidated data",
            "estimated_cost_usd_month": 99,
            "api_key_required": True,
            "paid_plan_required": True,
            "markets": "US equities",
            "resolution": "trade/quote/1m+",
            "history": "since 2016, extended hours",
            "backtest_ready": True,
            "forward_only": False,
            "status": "paid_not_configured",
            "limitations": "credentials and subscription required",
            "source_url": "https://docs.alpaca.markets/us/docs/about-market-data-api",
        },
        {
            "source": "Massive Stocks Basic",
            "dataset": "US equities minute aggregates",
            "estimated_cost_usd_month": 0,
            "api_key_required": True,
            "paid_plan_required": False,
            "markets": "US equities",
            "resolution": "1m aggregates",
            "history": "2 years, 100% market coverage",
            "backtest_ready": "exploratory",
            "forward_only": False,
            "status": "key_not_configured",
            "limitations": "5 calls/min; trades/quotes require higher plans",
            "source_url": "https://massive.com/pricing?product=stocks",
        },
        {
            "source": "Massive Stocks Starter/Developer",
            "dataset": "US equities aggregates and extended hours",
            "estimated_cost_usd_month": 29,
            "api_key_required": True,
            "paid_plan_required": True,
            "markets": "US equities",
            "resolution": "1s/1m depending plan",
            "history": "5 years at $29; 10 years at $79",
            "backtest_ready": True,
            "forward_only": False,
            "status": "paid_not_configured",
            "limitations": "news is a separate paid partner dataset",
            "source_url": "https://massive.com/pricing?product=stocks",
        },
        {
            "source": "Twelve Data",
            "dataset": "US equities, extended hours, earnings",
            "estimated_cost_usd_month": 0,
            "api_key_required": True,
            "paid_plan_required": "for earnings and full pre/post",
            "markets": "US and global equities",
            "resolution": "1m+",
            "history": "plan-dependent",
            "backtest_ready": "conditional",
            "forward_only": False,
            "status": "key_not_configured",
            "limitations": "earnings requires Grow; extended real-time requires Pro",
            "source_url": "https://twelvedata.com/pricing",
        },
    ]
    frame = pd.DataFrame(rows)
    frame.insert(0, "as_of", as_of)
    return frame
